name: Health check

pull_request:
  branches: [master]
  types: [opened, synchronize]

jobs:
  service_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: healthcheck
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://koskinentht-pokedex.herokuapp.com/
          max-attempts: 1